version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - airflow-network
  
  webserver:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:sua_senha@postgres:5432/seu_banco_de_dados
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - airflow-network

  scheduler:
    image: apache/airflow:latest
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://seu_usuario:sua_senha@postgres:5432/seu_banco_de_dados
    depends_on:
      - postgres
    networks:
      - airflow-network

networks:
  airflow-network:
    driver: bridge
